---

- name: Import docker-compose
  template:
    src: docker-compose.yml
    dest: "{{ application_directory }}/docker-compose.yml"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  notify: Restart docker compose

- name: Start docker-compose
  docker_compose:
    project_src: "{{ application_directory }}"