version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/repo/artifacts
      - run:
          name: Build image
          command: docker build -t "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" ~/repo/go
      - run:
          name: Save image in artifacts directory
          command: docker save "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" -o ~/repo/artifacts/image
      - persist_to_workspace:
          root: artifacts
          paths:
            - image

  push:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci/repo/artifacts
      - run:
          name: Load Docker image
          command: docker load -i artifacts/image
      - run:
          name: Connect to Docker hub
          command: docker login $REGISTRY_ENDPOINT --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD
      - run:
          name: Push Docker image
          command: docker push "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"


workflows:
  version: 2
  deploy:
    jobs:
      - build
      - push:
          requires:
            -build