version: "3"

services:
  application:
    image: "{{ application_docker_image }}:{{ application_docker_tag }}"
    ports:
      - "{{ application_port }}:8080"
    environment:
      REDIS_HOST: "{{ application_redis_host }}"
      REDIS_PORT: "{{ application_redis_port }}"