---

- name: Install common and docker
  hosts: tag_stage_production
  roles:
    - { role: common, become: yes }
    - { role: geerlingguy.docker, become: yes }

- name: Install web service
  hosts: "tag_component_application:&tag_stage_production"
  roles:
    - { role: application, tags: ["application"] }