---

- name: Install common and docker on staging
  hosts: tag_stage_staging
  roles:
    - { role: common, become: yes }
    - { role: geerlingguy.docker, become: yes }

- name: Install web service
  hosts: "tag_component_application:&tag_stage_staging"
  roles:
    - { role: application, tags: ["installApp"] }