---

- name: Install common and docker on staging
  hosts: tag_stage_staging
  become: yes
  roles:
    - { role: common }
    - { role: geerlingguy.docker }

- name: Install web service
  hosts: ["tag_component_application:&tag_stage_staging"]
  roles:
    - { role: application, tags: ["application"] }