application_redis_host: staging-technical-test-tp-cluster.2xhmpk.0001.euw2.cache.amazonaws.com
application_git_branch: master

application_docker_image: amauryfaveriel/tp-test-technique-go
application_docker_tag: 1.0